field.field.*.*.*.third_party.entity_reference_views_search:
  type: mapping
  label: 'Entity reference views search per bundle'
  mapping:
    status:
      type: boolean
      label: 'Use entity reference views search widget'
